### ISSUE TITLE
Acquire textures

### ISSUE THREAD

**Issue by ScottKillen** [ScottKillen/TreeMachine#7]
Fellow John Smith contributors,

I am working on this mod for Minecraft 1.12, which will feature tree breeding. I want to offer 32x textures out of the box, in the style of John Smith Modded.

I contributed textures to John Smith Modded for my Ancient Trees mod--but those were based on other textures in John-Smith Modded.

I would like to use recolored versions of those textures and a few other JSM tree textures--but I wanted to ask permission of all of you first.

If you grant permission, I would include a "Textured by John Smith Modded" or "Textured by John Smith Technicians Remix" link to the JS site on both the Github project and the CurseForge mod page.

I realize that JSM is not yet available for MC 1.12--however, I remember previous discussions among our team about how to increase visibility for JSM. This would help to that purpose.

If you prefer, I would be happy to use the new logo from this issue John-Smith-Modded/JSTR-Modded-1.7.x#155

I'd love to hear your feedback below. Thanks!

**Comment by goldbattle** [comment]
Hmm, I don't know if can be contained with your download. I would think that things need to stay on the official repos/domain/curse repositories.

I don't know if this is possible, but one option could be to download the files at run time (I know that is not optimal). This could allow for use of the textures but still providing the textures from the official source. I would think some sort of popup asking if the user wants to download the "recommended" JSTR textures so they can opt-in to download them (either open a link or automatically).

If the download fails, or if the user does not opt. into it then they could fallback on 16x textures. If you are going to include textures, it would have to be stated some place both in the mod and the website that the textures from from JSTR.

Just throwing ideas around based on the [license file](https://github.com/John-Smith-Modded/JSTR-Vanilla-1.9.x/blob/master/license.txt).

**Comment by ScottKillen** [comment]
Thanks, @goldbattle 

Additional work defeats the purpose...and runtime downloading/prompting is both difficult and controversial.

After posting this last night, I had a creative breakthrough and have been able to solve this without relying on JSTR derived work.

I appreciate your time in responding to this.
